apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# This configuration assumes your cluster has cert-manager configured and is using nginx for
# ingress.

bases:
    - ../../base

resources:
    - ingress.yaml


# The following patches update the domain name in the ingress without editing the yaml. 
# Modify it to your needs:
#patchesJson6902:
#    - patch: |-
#        - op: replace
#          path: /spec/rules/0/host
#          value: newregistry.mydomain.com
#        - op: replace
#          path: /spec/tls/0/hosts/0
#          value: newregistry.mydomain.com
#      target:
#          kind: Ingress
#          name: trow-ingress
#          group: extensions
#          version: v1beta1
