apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# This configuration assumes your cluster has cert-manager configured and is using nginx for
# ingress.

bases:
    - ../../base

resources:
    - ingress.yaml

