# This is the name of your environment. It should usually map to the project
# name.
name = "trow"

# Add packages from nixpkgs here. Use `nix search nixpkgs <term>` to find the
# package that you need.
#
# NOTE: don't forget to put commas between items! :)
packages = [
  "pkgconfig",
  "cmake",
  "perl",
  "go",
  "sqlite",
  "protobuf",
  "openssl",
  "valgrind",
]

# Message Of The Day (MOTD) is displayed when entering the environment with an
# interactive shell. By default it will show the project name.
#
# motd = ""

# Use this section to set environment variables to have in the environment.
#
# NOTE: all the values are escaped
[env]

# These are bash-specific configurations. The idea is to maybe support other
# shell environments in the future, although it is not the case right now.
[bash]

# Loaded after the environment setup. Useful to set dynamic environment
# variables.
extra = """
"""

# Only loaded in interactive shells. NOTE: `nix-shell -c "ls"` is interactive
interactive = """

"""

# Declare commands that are available in the environment.
[[commands]]
help = "a slick task runner"
name = "just"
category =  "utilities"
package = "just"

[[commands]]
help = "official kubernetes cli"
name = "kubectl"
category =  "utilities"
package = "kubectl"

[[commands]]
help = "official kubernetes config management tool"
name = "kustomize"
category =  "utilities"
package = "kustomize"

[[commands]]
help = "deep cluster insights"
name = "k9s"
category =  "utilities"
package = "k9s"

[[commands]]
help = "manage local dev cluster"
name = "k3d"
category =  "utilities"
package = "kube3d"

[[commands]]
help = "jq-ish for yaml files"
name = "yq"
category =  "utilities"
package = "yq-go"

[[commands]]
help = "see the task runner's recipes"
name = "just-menu"
command = "just --list"

[extensions]

dev-ca-path = "./dev/ca"

[extensions.static-dns]
"registry.local" = "127.0.0.1"
