apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# This will configure Trow for running on GKE, using the default ingress and a Google
# ManagedCertificate. You will need to point your (sub)domain DNS at the ingress IP address. It will
# take some time for the ingress and certificate to be provisioned.

namespace: trow

bases:
    - ../../base

resources:
    - cert.yaml # Needs to be updated with your domain name, see patches below.
    - ingress.yaml

# The following patch updates the certificate domain name without editing the yaml. 
# Modify it to your needs:

#patchesJson6902:
#    - patch: |-
#        - op: replace
#          path: /spec/domains/0
#          value: newregistry.mydomain.com
#      target:
#        kind: ManagedCertificate
#        name: trow-certificate
#        group: networking.gke.io
#        version: v1beta1
