apiVersion: rbac.authorization.k8s.io/v1
# Required cluster role to allow spire-agent to query k8s API server
kind: ClusterRole
metadata:
  name: spire-agent-cluster-role
rules:
- resources: ["pods", "nodes", "nodes/proxy"]
  apiGroups: [""]
  verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
# Binds above cluster role to spire-agent service account
kind: ClusterRoleBinding
metadata:
  name: spire-agent-cluster-role-binding
roleRef:
  name: spire-agent-cluster-role
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
subjects:
- name: spire-agent
  namespace: spire
  kind: ServiceAccount
