apiVersion: rbac.authorization.k8s.io/v1
# Required cluster role to allow spire-server to query k8s API server
kind: ClusterRole
metadata:
  name: spire-server-cluster-role
rules:
- resources: ["pods", "nodes"]
  apiGroups: [""]
  verbs: ["get"]
- resources: ["tokenreviews"]
  apiGroups: ["authentication.k8s.io"]
  verbs: ["create"]
---
apiVersion: rbac.authorization.k8s.io/v1
# Binds above cluster role to spire-server service account
kind: ClusterRoleBinding
metadata:
  name: spire-server-cluster-role-binding
roleRef:
  name: spire-server-cluster-role
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
subjects:
- name: spire-server
  namespace: spire
  kind: ServiceAccount
