apiVersion: v1
kind: Service
metadata:
  name: spire-server
  namespace: spire
spec:
  type: ClusterIP
  selector:
    app: spire-server
  ports:
  - name: grpc
    protocol: TCP
    port: 8081
    targetPort: 8081
