apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
    ./deployment-variant

# The following patches update the Deployment and transform it into a StatefulSet where
# images are persisted into a peristent volume claim.
#
# overlays use this StatefulSet variant as their base.
patchesJson6902:
- patch: |-
    - op: replace
      path: /metadata/name
      value: trow-set
    - op: replace
      path: /kind
      value: StatefulSet
    - op: add
      path: /spec/serviceName
      value: trow-svc
    - op: add
      path: /spec/volumeClaimTemplates
      value:
        - metadata:
            name: data-vol
          spec:
            accessModes: [ "ReadWriteOnce" ]
            resources:
              requests:
                storage: 20Gi
    - op: remove
      path: /spec/template/spec/volumes/1 # data-vol: emptyDir
  target:
    kind: Deployment
    name: trow-deploy
    group: apps
    version: v1

