apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: trow

# This will start Trow in a StatefulSet along with a persistent volume for data and a service that
# routes to it. 
#
# A working install will require an ingress forwarding a (sub)domain you control to this service.
# This install assumes the ingress terminates TLS; internally Trow is running over http only.
#
# The overlay directories include examples of how to provision ingress on various types of
# Kubernetes cluster.


resources: 
- stateful-set.yaml 
- service.yaml 

#- validate.yaml # Enable for validation webhook
  
images:
- name: containersol/trow
  newTag: "0.3"

