apiVersion: v1
kind: Service
metadata:
  name: trow-svc
spec:
  selector:
    app: trow
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: trow-http-port
  - name: https
    protocol: TCP
    port: 443
    targetPort: trow-https-port

