name: Build and Push Docker Images

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  build_images:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Default build
      run: |
        docker/build.sh
      
      
