name: Build and Push Docker Images

on:
  push:
    branches:
    - master

jobs:
  default_image:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Login to package repo
      run: |
          docker login docker.pkg.github.com -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }}
    - name: Install buildx
      run: |
          mkdir -p ~/.docker/cli-plugins
          curl -L -o ~/.docker/cli-plugins/docker-buildx https://github.com/docker/buildx/releases/download/v0.3.1/buildx-v0.3.1.linux-amd64
          chmod +x ~/.docker/cli-plugins/docker-buildx
    - name: Build and push multi-arch
      run: |
          ./docker/multi-arch.sh
          docker image prune -f --all
    - name: Build and push amd64 default target
      run: |
          ./docker/build.sh

