name: Build and Push Docker Images

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  default_image:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Login to package repo
      run: |
        docker login docker.pkg.github.com -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }}
    - name: Build multi-arch
      run: |
          export DOCKER_BUILDKIT=1
          export DOCKER_CLI_EXPERIMENTAL=enabled
          docker version
          docker/multi-arch.sh
    - name: Build amd64 default target
      run: |
        docker/build.sh
    - name: Push amd64 default 
      run: |
        docker tag containersol/trow:default docker.pkg.github.com/containersolutions/trow/trow:default
        docker push docker.pkg.github.com/containersolutions/trow/trow:default

