name: Tests

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  run_tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install latest nightly
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly-2020-04-07
        override: true
        default: true
        components: rustfmt
    - name: Install certs
      run: |
        cd quick-install/self-cert && ./make-certs.sh && cd ../..
        mkdir certs
        cp quick-install/self-cert/domain.crt ./certs/
        cp quick-install/self-cert/domain.key ./certs/
    - name: Add trow.test to hosts
      run: |
        echo "127.0.0.1 trow.test" | sudo tee -a /etc/hosts        
    - name: Run Cargo build
      uses: actions-rs/cargo@v1
      with:
        command: build
        args: --verbose --all
    - name: Run server lib test suite
      uses: actions-rs/cargo@v1
      with:
        command: test
        args: --verbose --manifest-path=lib/server/Cargo.toml
    - name: Run Trow test suite
      uses: actions-rs/cargo@v1
      with:
        command: test
        args: --verbose --all
    - name: Smoke test
      uses: actions-rs/cargo@v1
      with:
        command: test
        args: --verbose -- --ignored
      
      
